export const tasks = [
  {
    id: 1,
    title: "Passer l’aspirateur rez-de-chaussée",
    category: "🏠 Sols",
    points: 7,
    reminderDays: 4,
    emoji: "🧹",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: 2,
    title: "Passer l’aspirateur escaliers",
    category: "🏠 Sols",
    points: 5,
    reminderDays: 7,
    emoji: "🪜",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: 3,
    title: "Passer l’aspirateur étage",
    category: "🏠 Sols",
    points: 6,
    reminderDays: 7,
    emoji: "🧹",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: 4,
    title: "Lancer l’aspirateur robot rez-de-chaussée",
    category: "🏠 Sols",
    points: 2,
    reminderDays: 7,
    emoji: "🤖",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: 5,
    title: "Lancer l’aspirateur robot étage",
    category: "🏠 Sols",
    points: 5,
    reminderDays: 15,
    emoji: "🤖",
    color: "from-blue-500 to-cyan-500",
  },

  {
    id: 6,
    title: "Vider le sac à poussière de l’aspirateur",
    category: "🧰 Aspirateur classique",
    points: 3,
    reminderDays: 20,
    emoji: "🗑️",
    color: "from-slate-500 to-gray-700",
  },

  {
    id: 7,
    title: "Changer l’eau sale de l’aspirateur robot",
    category: "🤖 Aspirateur robot",
    points: 3,
    reminderDays: 20,
    emoji: "💧",
    color: "from-slate-500 to-gray-700",
  },
  {
    id: 8,
    title: "Entretenir l’aspirateur robot",
    category: "🤖 Aspirateur robot",
    points: 15,
    reminderDays: 30,
    emoji: "🛠️",
    color: "from-slate-500 to-gray-700",
  },
  {
    id: 9,
    title: "Vider le sac de l’aspirateur robot",
    category: "🤖 Aspirateur robot",
    points: 2,
    reminderDays: 20,
    emoji: "🗑️",
    color: "from-slate-500 to-gray-700",
  },

  {
    id: 10,
    title: "Faire les poussières rez-de-chaussée",
    category: "✨ Poussière & rangement",
    points: 5,
    reminderDays: 10,
    emoji: "🪶",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: 11,
    title: "Faire les poussières étage",
    category: "✨ Poussière & rangement",
    points: 3,
    reminderDays: 10,
    emoji: "🪶",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: 12,
    title: "Ranger une pièce de la maison",
    category: "✨ Poussière & rangement",
    points: 5,
    reminderDays: 9999,
    emoji: "📦",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: 13,
    title: "Trier les éléments de la chambre d’ami",
    category: "✨ Poussière & rangement",
    points: 7,
    reminderDays: 9999,
    emoji: "🧺",
    color: "from-purple-500 to-pink-500",
  },

  {
    id: 14,
    title: "Nettoyer une pièce de la maison",
    category: "🧼 Nettoyage pièces",
    points: 10,
    reminderDays: 9999,
    emoji: "🧽",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: 15,
    title: "Nettoyer le garage",
    category: "🧼 Nettoyage pièces",
    points: 15,
    reminderDays: 30,
    emoji: "🚗",
    color: "from-teal-500 to-cyan-500",
  },

  {
    id: 16,
    title: "Nettoyer les carreaux rez-de-chaussée",
    category: "🪟 Vitres",
    points: 15,
    reminderDays: 40,
    emoji: "🪟",
    color: "from-cyan-500 to-blue-700",
  },
  {
    id: 17,
    title: "Nettoyer les carreaux étage",
    category: "🪟 Vitres",
    points: 12,
    reminderDays: 40,
    emoji: "🪟",
    color: "from-cyan-500 to-blue-700",
  },

  {
    id: 18,
    title: "Remplir et lancer une machine à laver",
    category: "👕 Linge",
    points: 3,
    reminderDays: 2,
    emoji: "🧺",
    color: "from-indigo-500 to-purple-600",
  },
  {
    id: 19,
    title: "Étendre une machine à laver",
    category: "👕 Linge",
    points: 5,
    reminderDays: 9999,
    emoji: "👕",
    color: "from-indigo-500 to-purple-600",
  },
  {
    id: 20,
    title: "Ranger le linge sec",
    category: "👕 Linge",
    points: 3,
    reminderDays: 9999,
    emoji: "🧦",
    color: "from-indigo-500 to-purple-600",
  },
  {
    id: 21,
    title: "Trier les chaussettes",
    category: "👕 Linge",
    points: 15,
    reminderDays: 15,
    emoji: "🧦",
    color: "from-indigo-500 to-purple-600",
  },

  {
    id: 22,
    title: "Cuisiner un repas",
    category: "🍽️ Préparation",
    points: 6,
    reminderDays: 9999,
    emoji: "🍳",
    color: "from-orange-500 to-red-500",
  },
  {
    id: 23,
    title: "Préparer un dessert / gâteau / boisson",
    category: "🍽️ Préparation",
    points: 6,
    reminderDays: 9999,
    emoji: "🍰",
    color: "from-orange-500 to-red-500",
  },

  {
    id: 24,
    title: "Remplir le lave-vaisselle",
    category: "🍽️ Vaisselle",
    points: 3,
    reminderDays: 2,
    emoji: "🍽️",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: 25,
    title: "Vider le lave-vaisselle",
    category: "🍽️ Vaisselle",
    points: 6,
    reminderDays: 9999,
    emoji: "🍽️",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: 26,
    title: "Laver le filtre du lave-vaisselle",
    category: "🍽️ Vaisselle",
    points: 3,
    reminderDays: 20,
    emoji: "🧼",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: 27,
    title: "Mettre du sel dans le lave-vaisselle",
    category: "🍽️ Vaisselle",
    points: 3,
    reminderDays: 20,
    emoji: "🧂",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: 28,
    title: "Mettre du vinaigre dans le lave-vaisselle",
    category: "🍽️ Vaisselle",
    points: 3,
    reminderDays: 20,
    emoji: "🫙",
    color: "from-yellow-500 to-orange-500",
  },

  {
    id: 29,
    title: "Faire les courses",
    category: "🛒 Courses & entretien",
    points: 12,
    reminderDays: 7,
    emoji: "🛒",
    color: "from-green-500 to-emerald-700",
  },
  {
    id: 30,
    title: "Changer le filtre de la Brita",
    category: "🛒 Courses & entretien",
    points: 4,
    reminderDays: 30,
    emoji: "💧",
    color: "from-green-500 to-emerald-700",
  },

  {
    id: 31,
    title: "Nettoyer la douche",
    category: "🚽 Salle de bain",
    points: 12,
    reminderDays: 15,
    emoji: "🚿",
    color: "from-sky-500 to-blue-700",
  },
  {
    id: 32,
    title: "Nettoyer la baignoire",
    category: "🚽 Salle de bain",
    points: 6,
    reminderDays: 15,
    emoji: "🛁",
    color: "from-sky-500 to-blue-700",
  },
  {
    id: 33,
    title: "Nettoyer un toilette",
    category: "🚽 Salle de bain",
    points: 7,
    reminderDays: 15,
    emoji: "🚽",
    color: "from-sky-500 to-blue-700",
  },
  {
    id: 34,
    title: "Nettoyer un lavabo",
    category: "🚽 Salle de bain",
    points: 3,
    reminderDays: 15,
    emoji: "🪥",
    color: "from-sky-500 to-blue-700",
  },

  {
    id: 35,
    title: "Vider la poubelle",
    category: "🗑️ Déchets",
    points: 4,
    reminderDays: 10,
    emoji: "🗑️",
    color: "from-gray-500 to-slate-700",
  },
  {
    id: 36,
    title: "Sortir la poubelle verte",
  category: "🗑️ Déchets",
  points: 4,
  reminderDays: 9999,

  schedule: "weekly",
  day: 4,

  emoji: "🟢",
  color: "from-green-500 to-green-700",
},
{
  id: 57,
  title: "Sortir la poubelle jaune",
  category: "🗑️ Déchets",
  points: 5,
  reminderDays: 9999,

  schedule: "biweekly",
  day: 2,
  referenceWeek: 1,

  emoji: "🟡",
  color: "from-yellow-400 to-yellow-600",
},
  {
    id: 37,
    title: "Vider les poubelles de l’étage",
    category: "🗑️ Déchets",
    points: 7,
    reminderDays: 5,
    emoji: "🗑️",
    color: "from-gray-500 to-slate-700",
  },

  {
    id: 38,
    title: "Rajouter de l’eau dans la fontaine",
    category: "🐾 Chats",
    points: 2,
    reminderDays: 1,
    emoji: "💧",
    color: "from-pink-500 to-rose-700",
  },
  {
    id: 39,
    title: "Mettre de la pâté",
    category: "🐾 Chats",
    points: 3,
    reminderDays: 1,
    emoji: "🥫",
    color: "from-pink-500 to-rose-700",
  },
  {
    id: 40,
    title: "Remplir les croquettes",
    category: "🐾 Chats",
    points: 6,
    reminderDays: 2,
    emoji: "🐱",
    color: "from-pink-500 to-rose-700",
  },

  {
    id: 41,
    title: "Donner à boire et à manger aux oiseaux",
    category: "🐦 Oiseaux",
    points: 4,
    reminderDays: 1,
    emoji: "🐦",
    color: "from-emerald-500 to-green-700",
  },
  {
    id: 42,
    title: "Nettoyer le bureau des oiseaux",
    category: "🐦 Oiseaux",
    points: 15,
    reminderDays: 14,
    emoji: "🧽",
    color: "from-emerald-500 to-green-700",
  },

  {
    id: 43,
    title: "Faire la litière",
    category: "🐾 Entretien animaux",
    points: 10,
    reminderDays: 3,
    emoji: "🪣",
    color: "from-amber-500 to-orange-700",
  },

  {
    id: 44,
    title: "Nettoyer la terrasse",
    category: "🌿 Jardin & extérieur",
    points: 10,
    reminderDays: 20,
    emoji: "🪴",
    color: "from-green-500 to-lime-700",
  },
  {
    id: 45,
    title: "Tondre la pelouse",
    category: "🌿 Jardin & extérieur",
    points: 9,
    reminderDays: 14,
    emoji: "🌱",
    color: "from-green-500 to-lime-700",
  },
  {
    id: 46,
    title: "Désherber les mauvaises plantes",
    category: "🌿 Jardin & extérieur",
    points: 6,
    reminderDays: 14,
    emoji: "🌿",
    color: "from-green-500 to-lime-700",
  },
  {
    id: 47,
    title: "Tailler les haies et arbustes",
    category: "🌿 Jardin & extérieur",
    points: 15,
    reminderDays: 30,
    emoji: "✂️",
    color: "from-green-500 to-lime-700",
  },

  {
    id: 48,
    title: "Arroser les plantes intérieures",
    category: "💧 Arrosage",
    points: 4,
    reminderDays: 4,
    emoji: "🪴",
    color: "from-cyan-500 to-blue-700",
  },
  {
    id: 49,
    title: "Arroser les plantes extérieures",
    category: "💧 Arrosage",
    points: 2,
    reminderDays: 2,
    emoji: "🌼",
    color: "from-cyan-500 to-blue-700",
  },

  {
    id: 50,
    title: "Mettre du chlore",
    category: "🛁 Jacuzzi",
    points: 2,
    reminderDays: 7,
    emoji: "🧪",
    color: "from-blue-500 to-indigo-700",
  },
  {
    id: 51,
    title: "Mettre de l’anti-algue",
    category: "🛁 Jacuzzi",
    points: 2,
    reminderDays: 7,
    emoji: "🧪",
    color: "from-blue-500 to-indigo-700",
  },
  {
    id: 52,
    title: "Mettre de l’anticalcaire",
    category: "🛁 Jacuzzi",
    points: 2,
    reminderDays: 7,
    emoji: "🧪",
    color: "from-blue-500 to-indigo-700",
  },
  {
    id: 53,
    title: "Changer les filtres du jacuzzi",
    category: "🛁 Jacuzzi",
    points: 15,
    reminderDays: 30,
    emoji: "🛠️",
    color: "from-blue-500 to-indigo-700",
  },

  {
    id: 54,
    title: "Faire un feu de cheminée",
    category: "🔥 Cheminée",
    points: 6,
    reminderDays: 2,
    emoji: "🔥",
    color: "from-orange-500 to-red-700",
  },
  {
    id: 55,
    title: "Nettoyer la cheminée",
    category: "🔥 Cheminée",
    points: 12,
    reminderDays: 30,
    emoji: "🧹",
    color: "from-orange-500 to-red-700",
  },
  {
    id: 56,
    title: "Remplir le sac à bois de la cheminée",
    category: "🔥 Cheminée",
    points: 7,
    reminderDays: 5,
    emoji: "🪵",
    color: "from-orange-500 to-red-700",
  },
];